language: python
sudo: true
python:
    - "3.3"
    - "3.4"
    - "3.5"

addons:
    apt:
        packages:
        - graphviz

before_install:
  - export ROOT_DIR=`pwd`
  - sudo apt-get update -qq
  - sudo apt-get install -y mpich2 libmpich2-dev
  - sudo apt-get install -y liblapack-dev
  - sudo apt-get install -y fftw3-dev
  - sudo apt-get install -y gfortran
  - git clone -b async https://github.com/maxhutch/gslib.git
  - cd gslib
  - make
  - cd $HOME
  - git clone https://github.com/maxhutch/NekBox.git
  - git clone https://github.com/maxhutch/nek-analyze.git
  - cd $ROOT_DIR

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  - conda install pytest chest
  - pip install graphviz mapcombine
  - pip install git+https://github.com/maxhutch/dask --upgrade

  # Install dask
  - python setup.py install

script:
    - py.test nekpy --verbose

